GET http://localhost:3000/products/8.json

### All
GET http://localhost:3000/products/1.json

###Create
POST http://localhost:3000/products.json
Content-Type: application/json

    {
      "name": "",
      "price": "",
      "image_url": "google",
      "description": "SEE"
    }

### Update    
PATCH http://localhost:3000/products/8.json
Content-Type: application/json

    {
      "name": "",
      "price":"" ,
      "image_url": "google",
      "description": " "
      }

### Delete
DELETE http://localhost:3000/products/6.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}