GET http://localhost:3000/products/8.json

### All
GET http://localhost:3000/products/1.json

###Create
POST http://localhost:3000/products.json
Content-Type: application/json

    {
      "input_name": "Pen",
      "input_price": 10,
      "input_image_url": "google",
      "input_description": "Used to write stuff on gaming paper"
    }

### Update    
PATCH http://localhost:3000/products/8.json
Content-Type: application/json

    {
      "name": "Gun",
      "price": 10,
      "image_url": "google",
      "description": "Used to cause harm"
    }

### Delete
DELETE http://localhost:3000/products/6.json